<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>DigitalStarGate.Nina.DomeTelemetryExporter</AssemblyName>
    <RootNamespace>DigitalStarGate.Nina.DomeTelemetryExporter</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NINA.Plugin" Version="3.2.0.9001" />
    <PackageReference Include="NINA.Equipment" Version="3.2.0.9001" />
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
  </ItemGroup>
</Project>
