#!/usr/bin/env python3
import argparse,json
from pathlib import Path

def fmt(v,s=''): return 'n/d' if v is None else f'{v}{s}'
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--metrics',required=True); ap.add_argument('--output',required=True); a=ap.parse_args()
    m=json.loads(Path(a.metrics).read_text(encoding='utf-8')); n=m['nina']; p=m['phd2']; w=m['weather']; h=n['integration_seconds']/3600.0
    L=[f"# Report sessione {m['session_id']}",'',f"**Stato:** `{m['severity']}`",'','## Executive summary','','| KPI | Valore |','|---|---:|',f"| Pose LIGHT avviate | {n['light_started']} |",f"| Pose LIGHT completate | {n['light_completed']} |",f"| Pose LIGHT fallite esplicitamente | {n['light_failed_explicit']} |",f"| Pose LIGHT non abbinate/interrotte | {n['light_interrupted_unmatched']} |",f"| Esposizioni camera totali | {n['camera_exposures_total']} |",f"| Esposizioni tecniche stimate | {n['technical_exposures_estimated']} |",f"| Integrazione LIGHT totale | {h:.2f} h |",f"| Autofocus avviati | {n['autofocus_started']} |",f"| Autofocus completati | {n['autofocus_completed']} |",f"| Autofocus falliti esplicitamente | {n['autofocus_failed_explicit']} |",f"| Dither richiesti | {n['dither_requests']} |",f"| Segmenti di guida PHD2 | {p['guide_segments']} |",f"| Campioni guida validi | {p['guide_samples_valid']} |",f"| RMS AR | {fmt(p['rms_ra_arcsec'],' arcsec')} |",f"| RMS DEC | {fmt(p['rms_dec_arcsec'],' arcsec')} |",f"| RMS totale | {fmt(p['rms_total_arcsec'],' arcsec')} |",f"| Lost Star | {p['lost_star_events']} |",f"| PulseGuide failures | {p['pulse_guide_failures']} |",f"| Righe meteo (finestra completa) | {w['weather_rows_total']} |",f"| Righe meteo Unsafe (finestra completa) | {w['weather_rows_unsafe_full_window']} |",'','## Anomalie e osservazioni','']
    L += [f'- {x}' for x in m.get('severity_reasons',[])]
    L += ['','## Note metodologiche','','- Le esposizioni tecniche non sono conteggiate come pose LIGHT fallite.','- I segmenti PHD2 indicano avvii/arresti della guida e non sono automaticamente anomalie.','- I campioni PHD2 durante il settling sono esclusi dal calcolo RMS.','- Lo stato meteo Unsafe della finestra completa e informativo; la correlazione con sequenza attiva e cupola aperta sara introdotta nella versione successiva.','','## Passo successivo','','- `GREEN` o `YELLOW`: archiviazione ordinaria e verifica delle ottimizzazioni.','- `ORANGE` o `RED`: diagnostica di secondo livello e raccolta dei log specialistici.','']
    out=Path(a.output); out.parent.mkdir(parents=True,exist_ok=True); out.write_text('\n'.join(L),encoding='utf-8')
if __name__=='__main__': main()
