#!/usr/bin/env python3
import argparse,json
from pathlib import Path

def fmt(v,s=''): return 'n/d' if v is None else f'{v}{s}'
def fmt_sqm(v): return 'n/d' if v is None else f'{v:.4f} mag/arcsec²'
def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--metrics',required=True); ap.add_argument('--output',required=True); a=ap.parse_args()
    m=json.loads(Path(a.metrics).read_text(encoding='utf-8')); n=m['nina']; p=m['phd2']; w=m['weather']; sqm=m.get('sqm') or {}; h=n['integration_seconds']/3600.0
    L=[f"# Report sessione {m['session_id']}",'',f"**Stato:** `{m['severity']}`",'','## Executive summary','','| KPI | Valore |','|---|---:|',f"| Pose LIGHT avviate | {n['light_started']} |",f"| Pose LIGHT completate | {n['light_completed']} |",f"| Pose LIGHT fallite esplicitamente | {n['light_failed_explicit']} |",f"| Pose LIGHT non abbinate/interrotte | {n['light_interrupted_unmatched']} |",f"| Esposizioni camera totali | {n['camera_exposures_total']} |",f"| Esposizioni tecniche stimate | {n['technical_exposures_estimated']} |",f"| Integrazione LIGHT totale | {h:.2f} h |",f"| Autofocus avviati | {n['autofocus_started']} |",f"| Autofocus completati | {n['autofocus_completed']} |",f"| Autofocus falliti esplicitamente | {n['autofocus_failed_explicit']} |",f"| Dither richiesti | {n['dither_requests']} |",f"| Segmenti di guida PHD2 | {p['guide_segments']} |",f"| Profili PHD2 | {', '.join(p.get('equipment_profiles') or []) or 'n/d'} |",f"| Campioni guida totali | {fmt(p.get('guide_samples_total'))} |",f"| Campioni guida validi | {p['guide_samples_valid']} |",f"| Campioni saturi inclusi | {fmt(p.get('guide_samples_saturated'))} |",f"| Campioni rifiutati | {fmt(p.get('guide_samples_rejected'))} |",f"| Campioni esclusi durante settling | {fmt(p.get('guide_samples_settling_excluded'))} |",f"| Settling falliti | {fmt(p.get('settling_failures'))} |",f"| RMS AR | {fmt(p['rms_ra_arcsec'],' arcsec')} |",f"| RMS DEC | {fmt(p['rms_dec_arcsec'],' arcsec')} |",f"| RMS totale | {fmt(p['rms_total_arcsec'],' arcsec')} |",f"| Lost Star | {p['lost_star_events']} |",f"| PulseGuide failures | {p['pulse_guide_failures']} |",f"| SQM minimo | {fmt_sqm(sqm.get('min_mag_arcsec2'))} |",f"| SQM medio | {fmt_sqm(sqm.get('mean_mag_arcsec2'))} |",f"| SQM massimo | {fmt_sqm(sqm.get('max_mag_arcsec2'))} |",f"| Righe meteo (finestra completa) | {w['weather_rows_total']} |",f"| Righe meteo Unsafe (finestra completa) | {w['weather_rows_unsafe_full_window']} |",'','## Anomalie e osservazioni','']
    L += [f'- {x}' for x in m.get('severity_reasons',[])]
    L += ['','## Note metodologiche','','- Le esposizioni tecniche non sono conteggiate come pose LIGHT fallite.','- I segmenti PHD2 indicano avvii/arresti della guida e non sono automaticamente anomalie.','- L RMS PHD2 usa RARawDistance e DECRawDistance, convertiti in arcsec con la scala pixel dichiarata in ciascun segmento.','- I campioni PHD2 durante il settling sono esclusi; ErrorCode 0 e STAR_SATURATED (1) sono inclusi nel calcolo RMS e i saturi restano tracciati separatamente.','- I valori SQM minimo, medio e massimo provengono dalla proiezione canonica della sessione; `n/d` indica che la sessione non dispone di telemetria SQM storicizzata.','- La telemetria SQM e scientifica e non costituisce Safety Authority.','- Lo stato meteo Unsafe della finestra completa e informativo; la correlazione con sequenza attiva e cupola aperta sara introdotta nella versione successiva.','','## Passo successivo','','- `GREEN` o `YELLOW`: archiviazione ordinaria e verifica delle ottimizzazioni.','- `ORANGE` o `RED`: diagnostica di secondo livello e raccolta dei log specialistici.','']
    out=Path(a.output); out.parent.mkdir(parents=True,exist_ok=True); out.write_text('\n'.join(L),encoding='utf-8')
if __name__=='__main__': main()
