<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\DigitalStarGate.Contracts\DigitalStarGate.Contracts.csproj" />
    <ProjectReference Include="..\DigitalStarGate.Domain\DigitalStarGate.Domain.csproj" />
    <ProjectReference Include="..\DigitalStarGate.SharedKernel\DigitalStarGate.SharedKernel.csproj" />
  </ItemGroup>
</Project>
