using System.Reflection;
using System.Runtime.InteropServices;

[assembly: Guid("d1b4931c-0f31-44a4-a7f0-0b66a95e7f13")]
[assembly: AssemblyVersion("0.3.1.0")]
[assembly: AssemblyFileVersion("0.3.1.0")]
[assembly: AssemblyTitle("Digital StarGate Observatory Telemetry Exporter")]
[assembly: AssemblyDescription("Digital StarGate read-only observatory telemetry plugin for N.I.N.A.: unified monitoring of dome, mount, imaging camera, weather, safety observation, power, network connectivity and instrumental SQM sky brightness with scientific sample history.")]
[assembly: AssemblyCompany("Digital StarGate")]
[assembly: AssemblyProduct("Digital StarGate Observatory Telemetry Exporter")]
[assembly: AssemblyCopyright("Copyright 2026 Massimo Mainini / Digital StarGate")]
[assembly: AssemblyMetadata("Author", "Massimo Mainini")]
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
[assembly: AssemblyMetadata("Repository", "https://github.com/maininimassimo-bit/digital-stargate-manual")]
[assembly: AssemblyMetadata("Tags", "DigitalStarGate,observatory,dome,mount,camera,weather,safety,power,network,SQM,sky-quality,telemetry,history,read-only")]
[assembly: AssemblyMetadata("LongDescription", "**Author: Massimo Mainini**\n\nDigital StarGate Observatory Telemetry Exporter is the read-only telemetry integration plugin for the Digital StarGate observatory in N.I.N.A. It consolidates observatory status into a single local projection used by the Digital StarGate monitoring architecture.\n\nThe plugin observes and exports dome, mount, imaging camera, weather, N.I.N.A. SafetyMonitor observation, TS Shelter/J6 power evidence, network health and instrumental SQM sky brightness from the approved AAG CloudWatcher SOLO lightmpsas source. CURRENT instrumental SQM observations are also persisted to a local append-only NDJSON spool so downstream session reporting can calculate scientific history without coupling aggregation logic to N.I.N.A.\n\nAll realtime telemetry uses explicit CURRENT, STALE or UNKNOWN semantics. Invalid, unavailable or stale measurements fail to UNKNOWN/null rather than being estimated from proxy values. Historical SQM persistence is best-effort and cannot degrade realtime telemetry.\n\nThe plugin is strictly read-only: it does not command the dome, mount, camera, power system, router or CloudWatcher, does not modify equipment configuration and does not replace the local physical Safety Authority or observatory interlocks. SQM and other monitoring data are observability/scientific signals only and never authorize roof or equipment operations.")]
[assembly: ComVisible(false)]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
