using System.Reflection;
using System.Runtime.InteropServices;

[assembly: Guid("d1b4931c-0f31-44a4-a7f0-0b66a95e7f13")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyTitle("Digital StarGate Dome Telemetry Exporter")]
[assembly: AssemblyDescription("Read-only N.I.N.A. dome state projection for Digital StarGate Observatory Status")]
[assembly: AssemblyCompany("Digital StarGate")]
[assembly: AssemblyProduct("Digital StarGate Dome Telemetry Exporter")]
[assembly: AssemblyCopyright("Copyright 2026 Digital StarGate")]
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]
[assembly: AssemblyMetadata("License", "MPL-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.mozilla.org/en-US/MPL/2.0/")]
[assembly: AssemblyMetadata("Repository", "https://github.com/maininimassimo-bit/digital-stargate-manual")]
[assembly: AssemblyMetadata("Tags", "DigitalStarGate,dome,telemetry,observatory,read-only")]
[assembly: AssemblyMetadata("LongDescription", "Exports the dome snapshot already broadcast by N.I.N.A. to a local JSON projection. The plugin never connects to equipment and never issues dome commands.")]
[assembly: ComVisible(false)]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
